services:
  dailyhotapi:
    build:
      context: .
      target: runner
    ports:
      - "6688:6688"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=6688
    user: "114514"
    restart: always

  dailyhot-frontend:
    build:
      context: ../DailyHot
      args:
        - VITE_GLOBAL_API=https://dailyhotapi-production-6709.up.railway.app
    ports:
      - "6689:80"
    depends_on:
      - dailyhotapi
    restart: always
